# Conda environment configuration for the CPT Foundation Model project
# used with `conda env create -f environment.yml`
# delete existing environment with `conda env remove -n cpt-fm`
# Conda environment configuration for the CPT Foundation Model project
# used with `conda env create -f environment.yml`
name: cpt-fm

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Core Conda dependencies (NOTE: PyTorch is now handled by Pip)
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - libstdcxx-ng
  - pip # Ensure pip is installed by conda

  # Plotting
  - matplotlib
  - seaborn
  - plotly

  # For notebooks and experimentation
  - jupyter
  - notebook

  # Optional but recommended for Transformer models
  - transformers

  # Conda dependencies for MLflow ecosystem
  - pyyaml
  - joblib
  - tqdm

  # Pip dependencies for installing PyTorch for CUDA 12.8
  - pip:
    # First, specify the repository URL
    - --index-url https://download.pytorch.org/whl/cu128

    # Second, list the packages to install from that repository
    - torch
    - torchvision
    - torchaudio

    # tracking
    - mlflow

    # CPT IO
    - lasio
    
