# --- Paths ---
data_paths:
  input_file: 'data/raw/Database_CPT_PremstallerGeotechnik/CPT_PremstallerGeotechnik_revised.csv'
  processed_dir: 'data/processed/PG'
  scaler_path: 'data/processed/PG/scaler.joblib'
  model_save_path: 'models/foundation_model_PG.pth'

# --- Feature Engineering ---
# Maps your generic feature names to the specific column names in this dataset's CSV
feature_mapping:
  qc: 'qc (MPa)'
  fs: 'fs (kPa)'
  #u2: 'u2 (kPa)'
  #soil_class: 'Oberhollenzer_classes'

feature_map:
  qc: 0
  fs: 1

# --- Model Hyperparameters ---
model_params:
  num_features: 2 # 3 numerical + 22 soil classes (for example)
  model_dim: 64
  num_heads: 8
  num_layers: 4 # 4-8 is good range

# --- Data Splitting Parameters ---
data_split:
  train_ratio: 0.8  # 80% of the data for training
  val_ratio: 0.1    # 10% for validation. The rest (10%) will be for testing.
  random_seed: 42   # Seed for reproducible shuffling

# --- Training Hyperparameters ---
training_params:
  batch_size: 2
  learning_rate: 0.0001
  num_epochs: 20