# configs/dataset_A.yaml

# --- Paths ---
data_paths:
  input_file: 'data/raw/Database_CPT_PremstallerGeotechnik/CPT_PremstallerGeotechnik_revised.csv'
  processed_dir: 'data/processed/PG'
  scaler_path: 'data/processed/PG/scaler.joblib'
  model_save_path: 'models/foundation_model_PG.pth'

# --- Feature Engineering ---
# Maps your generic feature names to the specific column names in this dataset's CSV
feature_mapping:
  qc: 'qc (MPa)'
  fs: 'fs (kPa)'
  u2: 'u2 (kPa)'
  soil_class: 'Oberhollenzer_classes'

# --- Model Hyperparameters ---
model_params:
  num_features: 12 # 3 numerical + 22 soil classes (for example)
  model_dim: 128
  num_heads: 8
  num_layers: 4 # 4-8 is good range

# --- Training Hyperparameters ---
training_params:
  batch_size: 4 # was 32, adjusted to use less RAM
  learning_rate: 0.0001
  num_epochs: 50